a = dbgmodule.new("ntdll")
print("a name=",a:name())
print("a addr=",a:addr())
print("a NtCreateFile=", a.NtCreateFile)

b = dbgtype.new("ntdll!_peb", evalmasm("@$peb"))
print("_peb name=", b:name())
print("_peb addr=", b:addr())
print("_peb size=", b:size())
print("_peb ProcessParameters offset=", b:fieldoffset("ProcessParameters"))
print("_peb ProcessParameters type=", b:fieldtype("ProcessParameters"))
print("(*_peb.ProcessParameters).MaximumLength=", b.ProcessParameters:deref().MaximumLength)
print("_peb.AppCompatFlags.QuadPart=", b.AppCompatFlags.QuadPart)
print("_peb.UserSharedInfoPtr addr=", string.format("%x",b.UserSharedInfoPtr:addr()))
print("_peb.TlsExpansionBitmapBits[0]=", b.TlsExpansionBitmapBits[0])